services:
  liquidsoap:
    image: phasecorex/liquidsoap
    volumes:
      - ./liquidsoap/relay.liq:/app/relay.liq
    command: ["liquidsoap", "/app/relay.liq"]
    network_mode: "host"
    env_file:
      - .env

  backend:
    build: ./flask-backend
    ports:
      - "8080:8080"
    network_mode: "host"